version: '3.8'

services:
    brevets:
        build: brevets/.
        command: python flask_brevets.py
        ports: 
          - "5005:5000"
        depends_on:
          - brevetsdb
        environment:
            MONGODB_HOSTNAME: brevetsdb
    brevetsdb:
        image: mongo:5.0.5